import { Inter } from "next/font/google";
import "./globals.css";

import Transitionprovider from "@/components/Transitionprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Prasad Jadhav Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Transitionprovider>{children}</Transitionprovider>
      </body>
    </html>
  );
}
